### ISSUE TITLE
character bug

### ISSUE THREAD

**Issue by joggs** [SIMKL/script.simkl#15]
A bug I see now and then when it comes to python, unicode and my username.
My username in windows is jörgen which contains the special character ö. As you can see below python cannot handle that character and the result is that the path could not be found. I'm not having problems with other kodi plugins so there should be a solution for how to handle it correctly.

Error Contents: (2, 'No such file or directory', u'C:\\Users\\**J\xf6rgen**\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            Traceback (most recent call last):

**Comment by daviddavo** [comment]
Can you provide a more complete log?

**Comment by joggs** [comment]
20:26:38 T:26384   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', u'C:\\Users\\J\xf6rgen\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            Traceback (most recent call last):
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\service.py", line 11, in <module>
                                                from resources.lib import interface, engine
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\interface.py", line 7, in <module>
                                                from simklapi import api as API
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\simklapi.py", line 24, in <module>
                                                with open(USERFILE, "w") as f:
                                            IOError: (2, 'No such file or directory', u'C:\\Users\\J\xf6rgen\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            -->End of Python script error report<--
20:27:00 T:11104 WARNING: CPythonInvoker(7): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
20:27:01 T:11104   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', u'C:\\Users\\J\xf6rgen\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            Traceback (most recent call last):
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\simklapi.py", line 13, in <module>
                                                import interface
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\interface.py", line 7, in <module>
                                                from simklapi import api as API
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\simklapi.py", line 24, in <module>
                                                with open(USERFILE, "w") as f:
                                            IOError: (2, 'No such file or directory', u'C:\\Users\\J\xf6rgen\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            -->End of Python script error report<--
20:27:21 T:4000 WARNING: CPythonInvoker(8): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
20:27:21 T:4000   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', u'C:\\Users\\J\xf6rgen\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            Traceback (most recent call last):
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\simklapi.py", line 13, in <module>
                                                import interface
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\interface.py", line 7, in <module>
                                                from simklapi import api as API
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\simklapi.py", line 24, in <module>
                                                with open(USERFILE, "w") as f:
                                            IOError: (2, 'No such file or directory', u'C:\\Users\\J\xf6rgen\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            -->End of Python script error report<--
20:36:02 T:13712 WARNING: CPythonInvoker(9): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
20:36:02 T:13712   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', u'C:\\Users\\J\xf6rgen\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            Traceback (most recent call last):
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\simklapi.py", line 13, in <module>
                                                import interface
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\interface.py", line 7, in <module>
                                                from simklapi import api as API
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\simklapi.py", line 24, in <module>
                                                with open(USERFILE, "w") as f:
                                            IOError: (2, 'No such file or directory', u'C:\\Users\\J\xf6rgen\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            -->End of Python script error report<--
20:36:11 T:4780   ERROR: Unable to activate the previous window
20:36:14 T:4780  NOTICE: Storing total System Uptime

**Comment by daviddavo** [comment]
Can you test this and tell me if it works? 
[script.simkl.zip](https://github.com/SIMKL/script.simkl/files/737113/script.simkl.zip)

**Comment by joggs** [comment]
21:03:28 T:8412   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', 'C:\\Users\\J\xc3\xb6rgen\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            Traceback (most recent call last):
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\service.py", line 11, in <module>
                                                from resources.lib import interface, engine
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\interface.py", line 7, in <module>
                                                from simklapi import api as API
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\simklapi.py", line 21, in <module>
                                                with open(USERFILE, "w+") as f:
                                            IOError: (2, 'No such file or directory', 'C:\\Users\\J\xc3\xb6rgen\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            -->End of Python script error report<--
21:03:56 T:19832 WARNING: CPythonInvoker(8): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
21:03:56 T:19832   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', 'C:\\Users\\J\xc3\xb6rgen\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            Traceback (most recent call last):
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\simklapi.py", line 10, in <module>
                                                import interface
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\interface.py", line 7, in <module>
                                                from simklapi import api as API
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\simklapi.py", line 21, in <module>
                                                with open(USERFILE, "w+") as f:
                                            IOError: (2, 'No such file or directory', 'C:\\Users\\J\xc3\xb6rgen\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            -->End of Python script error report<--
21:04:08 T:13588   ERROR: Unable to activate the previous window
21:04:10 T:13588  NOTICE: Storing total System Uptime
21:04:10 T:13588  NOTICE: Saving settings
21:04:10 T:13588  NOTICE: stop all
21:04:10 T:13588  NOTICE: stop player
21:04:10 T:13588  NOTICE: ES: Stopping event server

**Comment by daviddavo** [comment]
Now the code uses ansii if you are on windows, and UTF-8 in Unix
[script.simkl.zip](https://github.com/SIMKL/script.simkl/files/737115/script.simkl.zip)

**Comment by joggs** [comment]
Less errors in log, but still some:

21:58:08 T:19276   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', 'C:\\Users\\J\xc3\xb6rgen\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            Traceback (most recent call last):
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\service.py", line 11, in <module>
                                                from resources.lib import interface, engine
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\interface.py", line 7, in <module>
                                                from simklapi import api as API
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\simklapi.py", line 21, in <module>
                                                with open(USERFILE, "w+") as f:
                                            IOError: (2, 'No such file or directory', 'C:\\Users\\J\xc3\xb6rgen\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            -->End of Python script error report<--

**Comment by daviddavo** [comment]
Last try... If this doesn't work, I'm afraid I'll have to try it on Windows by myself...
[script.simkl.zip](https://github.com/SIMKL/script.simkl/files/737146/script.simkl.zip)

**Comment by joggs** [comment]
Unfortunately not working:
22:23:14 T:8792   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', 'C:\\Users\\J\xc3\xb6rgen\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            Traceback (most recent call last):
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\service.py", line 11, in <module>
                                                from resources.lib import interface, engine
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\interface.py", line 7, in <module>
                                                from simklapi import api as API
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\simklapi.py", line 25, in <module>
                                                with open(USERFILE, "w+") as f:
                                            IOError: (2, 'No such file or directory', 'C:\\Users\\J\xc3\xb6rgen\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            -->End of Python script error report<--

**Comment by daviddavo** [comment]
Ok, I hope I have a Windows key somewhere...

**Comment by kat953162** [comment]
David- I would suggest using a front slash or something like that (from the looks of it, an escape key is / instead of \ and then failing)

**Comment by daviddavo** [comment]
Maybe this problem is the same as in #16 
Maybe the folder doesn't exist and is not an encoding problem. This forces the creation of the folder if it doesn't exist
[script.simkl.zip](https://github.com/SIMKL/script.simkl/files/739661/script.simkl.zip)

**Comment by joggs** [comment]
Still getting error.
I see that the script files actually are in the directory C:\Users\Jörgen\AppData\Roaming\Kodi\addons\script.simkl but that is because of my manually installed script from within kodi i suppose. That means that you have to navigate to that directory to be able to access the code i suppose.

No folder was created in the user directory.

errorlog:
0:30:59 T:24760   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', 'C:\\Users\\J\xc3\xb6rgen\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            Traceback (most recent call last):
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\service.py", line 11, in <module>
                                                from resources.lib import interface, engine
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\interface.py", line 7, in <module>
                                                from simklapi import api as API
                                              File "C:\Users\J��n\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\simklapi.py", line 25, in <module>
                                                with open(USERFILE, "w+") as f:
                                            IOError: (2, 'No such file or directory', 'C:\\Users\\J\xc3\xb6rgen\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            -->End of Python script error report<--

**Comment by joggs** [comment]
I am using the trakt script on this windows computer and it works, so maybe you can check that code for ideas.

**Comment by kat953162** [comment]
To be honest, it shouldn't depend on user directory, it should depend on Kodi "home" folder.

Then, no matter what complicated unicode username there is, Kodi ignores it and looks at its AppData directory.

**Comment by joggs** [comment]
http://forum.kodi.tv/showthread.php?tid=125492

**Comment by daviddavo** [comment]
Update your add-on from the repository and tell me if it works

**Comment by joggs** [comment]
It works David!
Great job indeed!
Did you have to do a workaround to make it work in the end or what was the solution?

**Comment by daviddavo** [comment]
The folder really didn't exist.
