### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by yura-pakhuchiy** [SIMKL/script.simkl#23]
Prints error when I press login button in settings.
Kodi 17 / Linux / Addon version 1.0.5 (latest from kodi repo)

**Comment by yura-pakhuchiy** [comment]
Same with latest git version.

```
07:21:18.461 T:140411867748096   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'ssl.SSLError'>
                                            Error Contents: [SSL] unknown error (_ssl.c:590)
                                            Traceback (most recent call last):
                                              File "/home/yura/.kodi/addons/script.simkl/service.py", line 44, in <module>
                                                API.api.login() #Add "remind me tomorrow button"
                                              File "/home/yura/.kodi/addons/script.simkl/resources/lib/simklapi.py", line 69, in login
                                                log.request("GET", url, headers=headers)
                                              File "/usr/lib/python2.7/httplib.py", line 1057, in request
                                                self._send_request(method, url, body, headers)
                                              File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
                                                self.endheaders(body)
                                              File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
                                                self._send_output(message_body)
                                              File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
                                                self.send(msg)
                                              File "/usr/lib/python2.7/httplib.py", line 859, in send
                                                self.connect()
                                              File "/usr/lib/python2.7/httplib.py", line 1278, in connect
                                                server_hostname=server_hostname)
                                              File "/usr/lib/python2.7/ssl.py", line 353, in wrap_socket
                                                _context=self)
                                              File "/usr/lib/python2.7/ssl.py", line 601, in __init__
                                                self.do_handshake()
                                              File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
                                                self._sslobj.do_handshake()
                                            SSLError: [SSL] unknown error (_ssl.c:590)
                                            -->End of Python script error report<--
07:21:18.516 T:140411867748096 WARNING: CPythonInvoker(6, /home/yura/.kodi/addons/script.simkl/service.py): the python script "/home/yura/.kodi/addons/script.simkl/service.py" has left sever
al classes in memory that we couldn't clean up. The classes include: N14PythonBindings30XBMCAddon_xbmc_Player_DirectorE,N9XBMCAddon9xbmcaddon5AddonE
07:21:18.516 T:140411823683328 WARNING: CPythonInvoker(10): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in
future version.

...

07:21:42.723 T:140412054353664 WARNING: CPythonInvoker(11): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in
future version.
07:21:43.744 T:140412054353664   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'socket.error'>
                                            Error Contents: [Errno 0] Error
                                            Traceback (most recent call last):
                                              File "/home/yura/.kodi/addons/script.simkl/resources/lib/simklapi.py", line 221, in <module>
                                                api.login()
                                              File "/home/yura/.kodi/addons/script.simkl/resources/lib/simklapi.py", line 69, in login
                                                log.request("GET", url, headers=headers)
                                              File "/usr/lib/python2.7/httplib.py", line 1057, in request
                                                self._send_request(method, url, body, headers)
                                              File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
                                                self.endheaders(body)
                                              File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
                                                self._send_output(message_body)
                                              File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
                                                self.send(msg)
                                              File "/usr/lib/python2.7/httplib.py", line 859, in send
                                                self.connect()
                                              File "/usr/lib/python2.7/httplib.py", line 1278, in connect
                                                server_hostname=server_hostname)
                                              File "/usr/lib/python2.7/ssl.py", line 353, in wrap_socket
                                                _context=self)
                                              File "/usr/lib/python2.7/ssl.py", line 601, in __init__
                                                self.do_handshake()
                                              File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
                                                self._sslobj.do_handshake()
                                            error: [Errno 0] Error
                                            -->End of Python script error report<--
07:21:45.310 T:140412054353664 WARNING: CPythonInvoker(13): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in
future version.
07:21:46.274 T:140412054353664   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'socket.error'>
                                            Error Contents: [Errno 0] Error
                                            Traceback (most recent call last):
                                              File "/home/yura/.kodi/addons/script.simkl/resources/lib/simklapi.py", line 221, in <module>
                                                api.login()
                                              File "/home/yura/.kodi/addons/script.simkl/resources/lib/simklapi.py", line 69, in login
                                                log.request("GET", url, headers=headers)
                                              File "/usr/lib/python2.7/httplib.py", line 1057, in request
                                                self._send_request(method, url, body, headers)
                                              File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
                                                self.endheaders(body)
                                              File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
                                                self._send_output(message_body)
                                              File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
                                                self.send(msg)
                                              File "/usr/lib/python2.7/httplib.py", line 859, in send
                                                self.connect()
                                              File "/usr/lib/python2.7/httplib.py", line 1278, in connect
                                                server_hostname=server_hostname)
                                              File "/usr/lib/python2.7/ssl.py", line 353, in wrap_socket
                                                _context=self)
                                              File "/usr/lib/python2.7/ssl.py", line 601, in __init__
                                                self.do_handshake()
                                              File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
                                                self._sslobj.do_handshake()
                                            error: [Errno 0] Error
                                            -->End of Python script error report<--
07:21:48.974 T:140412054353664 WARNING: CPythonInvoker(14): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in
future version.
07:21:50.137 T:140412054353664   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'socket.error'>
                                            Error Contents: [Errno 0] Error
                                            Traceback (most recent call last):
                                              File "/home/yura/.kodi/addons/script.simkl/resources/lib/simklapi.py", line 221, in <module>
                                                api.login()
                                              File "/home/yura/.kodi/addons/script.simkl/resources/lib/simklapi.py", line 69, in login
                                                log.request("GET", url, headers=headers)
                                              File "/usr/lib/python2.7/httplib.py", line 1057, in request
                                                self._send_request(method, url, body, headers)
                                              File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
                                                self.endheaders(body)
                                              File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
                                                self._send_output(message_body)
                                              File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
                                                self.send(msg)
                                              File "/usr/lib/python2.7/httplib.py", line 859, in send
                                                self.connect()
                                              File "/usr/lib/python2.7/httplib.py", line 1278, in connect
                                                server_hostname=server_hostname)
                                              File "/usr/lib/python2.7/ssl.py", line 353, in wrap_socket
                                                _context=self)
                                              File "/usr/lib/python2.7/ssl.py", line 601, in __init__
                                                self.do_handshake()
                                              File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
                                                self._sslobj.do_handshake()
                                            error: [Errno 0] Error
                                            -->End of Python script error report<--

```

Internet works fine, time is set correctly, I do not have SSL errors in browser.

**Comment by daviddavo** [comment]
I've been having a bit of problem with the API recently. I think is an API's bug

**Comment by masyk** [comment]
The API should be fixed now, please try now.
